## Step 1: Import libraries & Dataset

In [1]:
#import libraries
import pandas as pd
import numpy as np

# Display Setting

# Show all columns
pd.set_option('display.max_columns', None)

# Show full column width
pd.set_option('display.max_colwidth', None)

# Adjust display width
pd.set_option('display.width', None)

In [2]:
# Load CSV with latin1 encoding
df = pd.read_csv('Superstore.csv', encoding='latin1')

df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs, Rounded Back",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters by Universal,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

## Step 2. Inspect Data

In [3]:
# Shape of Dataset
print(f'Shape of Dataset : {df.shape}')

# Column info
print('\n Information of Dataset :')
df.info()

# Data types
print('\n Datatypes :')
print(df.dtypes)

 # Statistics
print('\n Statistics of Dataset :')
df.describe()

Shape of Dataset : (9994, 21)

 Information of Dataset :
<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   str
 3   Ship Date      9994 non-null   str
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), str(15)
memory usage: 1.6 MB

 Datatypes :
Row ID             int64
Order ID             str
Order Date           str
Ship Date            str
Ship Mode            str
Customer ID          str
Customer Name        str
Segment              str
Country              str
City                 str
State                str
Postal Code        int64
Region               str
Product ID           str
Category             str
Sub-Category         str
Product Name         str
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

 Statistics of Dataset :

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858001,3.789574,0.156203,28.656896
std,2885.163629,32063.693350,623.245101,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

## Step 3. Data Cleaning

### - Checking Null Values

In [4]:
# Checking Null Values
print(df.isnull().sum())

print('\nChecked for null values and no missing values were found.')

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

Checked for null values and no missing values were found.

### - Fixing Column Names

In [5]:
# Checking Column names
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='str')

In [6]:
# Standardize column names for easier analysis and coding
df.columns = df.columns.str.replace(' ', '_').str.replace('-', '_').str.lower().str.strip()

In [7]:
# Columns names after fixing them
df.columns

Index(['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode',
       'customer_id', 'customer_name', 'segment', 'country', 'city', 'state',
       'postal_code', 'region', 'product_id', 'category', 'sub_category',
       'product_name', 'sales', 'quantity', 'discount', 'profit'],
      dtype='str')

In [8]:
# Dropping unnecessary Columns
df.drop('row_id', axis=1, inplace=True)

### - Handling duplicate records

In [9]:
# Duplicate rows count
df.duplicated(subset=['order_id', 'product_id']).sum()

np.int64(8)

In [10]:
# Show duplicate order_id + product_id records
duplicates = df[df.duplicated(subset = ['order_id', 'product_id'], keep=False)]

duplicates.sort_values(['order_id', 'product_id'])

,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,state,postal_code,region,product_id,category,sub_category,product_name,sales,quantity,discount,profit
6498,CA-2015-103135,7/24/2015,7/28/2015,Standard Class,SS-20515,Shirley Schmidt,Home Office,United States,Louisville,Kentucky,40214,South,OFF-BI-10000069,Office Supplies,Binders,"GBC Prepunched Paper, 19-Hole, for Binding Systems, 24-lb",135.090,9,0.0,62.1414
6500,CA-2015-103135,7/24/2015,7/28/2015,Standard Class,SS-20515,Shirley Schmidt,Home Office,United States,Louisville,Kentucky,40214,South,OFF-BI-10000069,Office Supplies,Binders,"GBC Prepunched Paper, 19-Hole, for Binding Systems, 24-lb",90.060,6,0.0,41.4276
350,CA-2016-129714,9/1/2016,9/3/2016,First Class,AB-10060,Adam Bellavance,Home Office,United States,New York City,New York,10009,East,OFF-PA-10001970,Office Supplies,Paper,Xerox 1881,24.560,2,0.0,11.5432
352,CA-2016-129714,9/1/2016,9/3/2016,First Class,AB-10060,Adam Bellavance,Home Office,United States,New York City,New York,10009,East,OFF-PA-10001970,Office Supplies,Paper,Xerox 1881,49.120,4,0.0,23.0864
1300,CA-2016-137043,12/23/2016,12/25/2016,Second Class,LC-17140,Logan Currie,Consumer,United States,Springfield,Virginia,22153,South,FUR-FU-10003664,Furniture,Furnishings,"Electrix Architect's Clamp-On Swing Arm Lamp, Black",572.760,6,0.0,166.1004
1301,CA-2016-137043,12/23/2016,12/25/2016,Second Class,LC-17140,Logan Currie,Consumer,United States,Springfield,Virginia,22153,South,FUR-FU-10003664,Furniture,Furnishings,"Electrix Architect's Clamp-On Swing Arm Lamp, Black",286.380,3,0.0,83.0502
9168,CA-2016-140571,3/15/2016,3/19/2016,Standard Class,SJ-20125,Sanjit Jacobs,Home Office,United States,Jackson,Mississippi,39212,South,OFF-PA-10001954,Office Supplies,Paper,Xerox 1964,319.760,14,0.0,147.0896
9169,CA-2016-140571,3/15/2016,3/19/2016,Standard Class,SJ-20125,Sanjit Jacobs,Home Office,United States,Jackson,Mississippi,39212,South,OFF-PA-10001954,Office Supplies,Paper,Xerox 1964,45.680,2,0.0,21.0128
7881,CA-2017-118017,12/3/2017,12/6/2017,Second Class,LC-16870,Lena Cacioppo,Consumer,United States,Thornton,Colorado,80229,West,TEC-AC-10002006,Technology,Accessories,Memorex Micro Travel Drive 16 GB,76.752,6,0.2,10.5534
7882,CA-2017-118017,12/3/2017,12/6/2017,Second Class,LC-16870,Lena Cacioppo,Consumer,United States,Thornton,Colorado,80229,West,TEC-AC-10002006,Technology,Accessories,Memorex Micro Travel Drive 16 GB,102.336,8,0.2,14.0712
3183,CA-2017-152912,11/9/2017,11/12/2017,Second Class,BM-11650,Brian Moss,Corporate,United States,Columbia,Maryland,21044,East,OFF-ST-10003208,Office Supplies,Storage,Adjustable Depth Letter/Legal Cart,1633.140,9,0.0,473.6106
3184,CA-2017-152912,11/9/2017,11/12/2017,Second Class,BM-11650,Brian Moss,Corporate,United States,Columbia,Maryland,21044,East,OFF-ST-10003208,Office Supplies,Storage,Adjustable Depth Letter/Legal Cart,544.380,3,0.0,157.8702
3405,US-2014-150119,4/23/2014,4/27/2014,Standard Class,LB-16795,Laurel Beltran,Home Office,United States,Columbus,Ohio,43229,East,FUR-CH-10002965,Furniture,Chairs,"Global Leather Highback Executive Chair with Pneumatic Height Adjustment, Black",281.372,2,0.3,-12.0588
3406,US-2014-150119,4/23/2014,4/27/2014,Standard Class,LB-16795,Laurel Beltran,Home Office,United States,Columbus,Ohio,43229,East,FUR-CH-10002965,Furniture,Chairs,"Global Leather Highback Executive Chair with Pneumatic Height Adjustment, Black",281.372,2,0.3,-12.0588
430,US-2016-123750,4/15/2016,4/21/2016,Standard Class,RB-19795,Ross Baird,Home Office,United States,Gastonia,North Carolina,28052,South,TEC-AC-10004659,Technology,Accessories,Imation Secure+ Hardware Encrypted USB 2.0 Flash Drive; 16GB,408.744,7,0.2,76.6395
431,US-2016-123750,4/15/2016,4/21/2016,Standard Class,RB-19795,Ross Baird,Home Office,United States,Gastonia,North Carolina,28052,South,TEC-AC-10004659,Technology,Accessories,Imation Secure+ Hardware Encrypted USB 2.0 Flash Drive; 16GB,291.960,5,0.2,54.7425

In [11]:
# Merge duplicate records and sum quantity, sales and profit values.

df = df.groupby(
    [col for col in df.columns if col not in ['quantity', 'sales', 'profit']], as_index=False).agg({
    'quantity' : 'sum',
    'sales' : 'sum',
    'profit' : 'sum'
    })

In [12]:
print(f'Shape After Merging :{df.shape}')

Shape After Merging :(9986, 20)

### - DATA TYPE CONVERSION

In [13]:
# Convert Date columns into Date time format

df['order_date'] = pd.to_datetime(df['order_date'], format = '%m/%d/%Y')
df['ship_date'] = pd.to_datetime(df['ship_date'], format = '%m/%d/%Y')

In [14]:
# Convert categorical (object) columns into category datatype to reduce memory usage and improve analysis efficiency.

cat_cols = ['ship_mode', 'segment', 'country', 'city', 'state', 'region', 'category', 'sub_category']

for col in cat_cols:
    df[col] = df[col].astype('category')

In [15]:
# Column datatypes after converting them.
df.dtypes

order_id                    str
order_date       datetime64[us]
ship_date        datetime64[us]
ship_mode              category
customer_id                 str
customer_name               str
segment                category
country                category
city                   category
state                  category
postal_code               int64
region                 category
product_id                  str
category               category
sub_category           category
product_name                str
discount                float64
quantity                  int64
sales                   float64
profit                  float64
dtype: object

### - Creating New Features

In [16]:
# Calculate shipping time in days
df['days_to_ship'] = (df['ship_date'] - df['order_date']).dt.days

# Extract Year
df['year'] = df['order_date'].dt.year

# Extract Month
df['month'] = df['order_date'].dt.month_name()

# Create a quarter column from Order Date
df['order_quarter'] = df['order_date'].dt.quarter

In [17]:
df['profit_category'] = df['profit'].apply(lambda x: 'Profit' if x > 0 else 'Loss')

### - Save cleaned data in csv format

In [18]:
df.to_csv('superstore_cleaned.csv', index=False)
print('File saved!')

File saved!